[package]
name = "ergibus_lib"
version = "0.2.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]
edition = "2024"

[dependencies]
chrono = "0.4"
dirs = "3.0"
fs2 = "0.4"
globset = "0.1"
hostname = "0.4"
lazy_static = "1.5"
libc = "*"
log = "0.4"
regex = "1.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
snap = "1"
tempdir = "0.3"
users = "0.11"
walkdir = "2.5"
window-sort-iterator = "0.1.0"

dychatat_lib = { path = "../dychatat_lib" }
path_utilities = { git = "https://github.com/pwil3058/rust_utilities" }
